// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6lE40tqDKGj3GtC77IX_AMyYBty5Jtc',
    appId: '1:85949404610:web:ab81d515ed000e9adc725b',
    messagingSenderId: '85949404610',
    projectId: 'sandrop-eae65',
    authDomain: 'sandrop-eae65.firebaseapp.com',
    storageBucket: 'sandrop-eae65.firebasestorage.app',
    measurementId: 'G-98Z3RJMKYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8A8WAMKbRSuMUOCVyLibX9XWd-NYRdoQ',
    appId: '1:85949404610:android:c58dab0f507196e2dc725b',
    messagingSenderId: '85949404610',
    projectId: 'sandrop-eae65',
    storageBucket: 'sandrop-eae65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIx9R8Vy8YGc375wwAtrnnsGkNf9c3uE',
    appId: '1:85949404610:ios:7a5730fcf33992d2dc725b',
    messagingSenderId: '85949404610',
    projectId: 'sandrop-eae65',
    storageBucket: 'sandrop-eae65.firebasestorage.app',
    iosBundleId: 'com.example.sandrofp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIx9R8Vy8YGc375wwAtrnnsGkNf9c3uE',
    appId: '1:85949404610:ios:7a5730fcf33992d2dc725b',
    messagingSenderId: '85949404610',
    projectId: 'sandrop-eae65',
    storageBucket: 'sandrop-eae65.firebasestorage.app',
    iosBundleId: 'com.example.sandrofp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6lE40tqDKGj3GtC77IX_AMyYBty5Jtc',
    appId: '1:85949404610:web:c882f6f12304d745dc725b',
    messagingSenderId: '85949404610',
    projectId: 'sandrop-eae65',
    authDomain: 'sandrop-eae65.firebaseapp.com',
    storageBucket: 'sandrop-eae65.firebasestorage.app',
    measurementId: 'G-7R89P25Q3N',
  );

}