// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOB5fsKpGMFq5cxWJLp2M5b5cdMWh-5NU',
    appId: '1:749908221061:web:823fe8ad9d11b32b24ddec',
    messagingSenderId: '749908221061',
    projectId: 'alyse-rose',
    authDomain: 'alyse-rose.firebaseapp.com',
    storageBucket: 'alyse-rose.firebasestorage.app',
    measurementId: 'G-6TB4MYQJRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVA8HOshOwZQOKsHklW7uQqCWQ2cZPro0',
    appId: '1:749908221061:android:57e984f1d8dc30c324ddec',
    messagingSenderId: '749908221061',
    projectId: 'alyse-rose',
    storageBucket: 'alyse-rose.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJKYsVJNjRl5HTuAfml1G6amxSsQMi1o',
    appId: '1:749908221061:ios:0206701ea5dd16b124ddec',
    messagingSenderId: '749908221061',
    projectId: 'alyse-rose',
    storageBucket: 'alyse-rose.firebasestorage.app',
    iosBundleId: 'com.example.alyseRoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJKYsVJNjRl5HTuAfml1G6amxSsQMi1o',
    appId: '1:749908221061:ios:0206701ea5dd16b124ddec',
    messagingSenderId: '749908221061',
    projectId: 'alyse-rose',
    storageBucket: 'alyse-rose.firebasestorage.app',
    iosBundleId: 'com.example.alyseRoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOB5fsKpGMFq5cxWJLp2M5b5cdMWh-5NU',
    appId: '1:749908221061:web:0cc105fd81101eb224ddec',
    messagingSenderId: '749908221061',
    projectId: 'alyse-rose',
    authDomain: 'alyse-rose.firebaseapp.com',
    storageBucket: 'alyse-rose.firebasestorage.app',
    measurementId: 'G-D7F0MY0BTE',
  );
}
